# Generated by Django 3.0.5 on 2020-05-03 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slogger', '0002_diaryentry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='date_rage_days',
            field=models.IntegerField(default=14, verbose_name='Default summary date range'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slogger.Child'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='diapers_enabled',
            field=models.BooleanField(default=False, verbose_name='Draw sleep data in graph by default'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='meals_enabled',
            field=models.BooleanField(default=False, verbose_name='Draw sleep data in graph by default'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='paginate_by',
            field=models.IntegerField(default=20, verbose_name='Paginate by'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sleep_enabled',
            field=models.BooleanField(default=True, verbose_name='Draw sleep data in graph by default'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
