# Generated by Django 3.0.5 on 2020-05-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slogger', '0003_auto_20200503_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='date_rage_days',
            new_name='date_range_days',
        ),
    ]
