# Generated by Django 3.0.5 on 2020-05-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slogger', '0004_auto_20200504_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='histogram_factor_md',
            field=models.IntegerField(default=6, verbose_name='Time factor for meals+diapers in histogram'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='histogram_raster',
            field=models.IntegerField(default=10, verbose_name='Time raster for histogram (minutes)'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='start_hour_day',
            field=models.IntegerField(default=8, verbose_name='Day starts at (h)'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='start_hour_night',
            field=models.IntegerField(default=19, verbose_name='night starts at (h)'),
        ),
    ]
