# Generated by Django 3.0.5 on 2020-05-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slogger', '0005_auto_20200505_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='diapers_enabled',
            field=models.BooleanField(default=False, verbose_name='Draw diaper data in graph by default'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='meals_enabled',
            field=models.BooleanField(default=False, verbose_name='Draw meal data in graph by default'),
        ),
    ]
