# Generated by Django 3.0.5 on 2020-05-10 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slogger', '0006_auto_20200506_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added on')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('m_type', models.CharField(choices=[('L', 'Length/Height'), ('W', 'Weight')], max_length=1)),
                ('day', models.IntegerField()),
                ('p01', models.FloatField()),
                ('p1', models.FloatField()),
                ('p3', models.FloatField()),
                ('p5', models.FloatField()),
                ('p10', models.FloatField()),
                ('p15', models.FloatField()),
                ('p25', models.FloatField()),
                ('p50', models.FloatField()),
                ('p75', models.FloatField()),
                ('p85', models.FloatField()),
                ('p90', models.FloatField()),
                ('p95', models.FloatField()),
                ('p97', models.FloatField()),
                ('p99', models.FloatField()),
                ('p999', models.FloatField()),
            ],
        ),
    ]
