# Generated by Django 3.0.5 on 2020-05-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slogger', '0007_percentile'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='dt_end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eaten until'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight (kg)'),
        ),
    ]
