# Generated by Django 3.0.5 on 2020-05-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slogger', '0008_auto_20200521_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='use_new_ui',
            field=models.BooleanField(default=False, verbose_name='Use new UI variant'),
        ),
    ]
