# Generated by Django 3.0.5 on 2020-05-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slogger', '0009_usersettings_use_new_ui'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaper',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='meal',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='sleepphase',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Comment'),
        ),
    ]
