# Generated by Django 3.0.5 on 2020-05-24 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import slogger.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slogger', '0010_auto_20200524_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, slogger.mixins.AttributeModelMixin),
        ),
        migrations.AddField(
            model_name='diaper',
            name='diaper_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slogger.DiaperType'),
        ),
    ]
